### PR TITLE
Johnbrichetto/may 2024 upstream sync

### PR DESCRIPTION
**Pull request by jbrichetto**

### CODE REVIEW

**Comment by jbrichetto** [comment]
for this change, I:

1. pulled the latest from the upstream branch
2. rebased this branch off of that
3. cherry picked Matt's PR to support unescaped header auth (https://github.com/golang/oauth2/pull/476/files#diff-94d3412326302fbf2a431681462f6938bb0c80991614e7fce58bda661da787b6)
4. updated the test functions he added there to no longer use a function that was removed from the library, set up the style cache the same way as other tests are currently configured

**---If you're reading this in the future---**

please follow the steps above in your PR except cherry-pick the modified version of matt's change below (06b838ad494e0bd6c1243a536e637636904d84a1) which contains updated tests

**Comment by bdimcheff** [comment]
can you squash matt+your changes into a single commit because we're definitely gonna have to cherry pick it again

**Comment by jbrichetto** [comment]
> can you squash matt+your changes into a single commit because we're definitely gonna have to cherry pick it again

Done! Although the repo was mad that there were secrets in these places:

—— Amazon AWS Secret Access Key ——————————————————————
remote:        locations:
remote:          - commit: 762b55d513068e2fa05fe66da5797a1a3cd3bf34
remote:            path: google/externalaccount/aws_test.go:48
remote:          - commit: caa5313130b8b1f76527ae6aa938b527c5cfe69b
remote:            path: google/internal/externalaccount/aws_test.go:47
remote:          - commit: 7ec4f7728225eb94ae72d28499512ed6b23d06f8
remote:            path: google/internal/externalaccount/aws_test.go:47

but those are in the google maintained repo, i didnt introduce them, and they are just test files. so i overrode the security setting and told it to let me commit.

just noting here in case a security team member sees that I did that

**Review by bdimcheff — APPROVED** [review]

**Comment by jbrichetto** [comment]
verified that both the backfiller and coreservices can build after these updates ✅

**Pull request merged**
